mitodl/ocw-hugo-projects

ocw-www/ocw-studio.yaml
Closes https://github.com/mitodl/ocw-hugo-projects/issues/3
In https://github.com/mitodl/ocw-studio/pull/297, we added an endpoint to `ocw-studio` for a webhook that will consume `ocw-studio.yaml` files and create / update `WebsiteStarter` objects based on the configuration contained in said file.  This PR adds the types of content supported by the `www` theme in `ocw-hugo-themes` (https://github.com/mitodl/ocw-hugo-themes/tree/main/www/archetypes) to the `ocw-www` project's `ocw-studio.yaml` configuration.
The best way to test this is to import it into `ocw-studio` using the Github webhook integration.  In order to do that we will need to:
- Create a public repo with the content's of this branch (`cg/ocw-www-starter`) to test the webhook from
- Clone `ocw-studio` and follow the readme to …
=> ocw-www starter

ocw-course/ocw-studio.yaml, ocw-www/ocw-studio.yaml
Fixes #14 
Fixes #16 
Fixes #15
=> Add instructor collection

ocw-course/ocw-studio.yaml, ocw-www/ocw-studio.yaml
No issue, just a text change. OCW authors are more familiar with "ALT Text"  
Changes the label for images to "ALT Text"
Load the config into studio? Is it safe to change the label on a field, or will we need a migration & a theme change?
=> fix: Text Alternative => ALT text

ocw-course/ocw-studio.yaml
Closes https://github.com/mitodl/ocw-hugo-projects/issues/56
Adds video metadata fields
Convert to JSON, create or update a starter with this config, and create new video resources for a website based on the starter.
https://docs.google.com/document/d/1rAFX8VMaT5EN_1aJqTlEP6SHrBU-5m6zg8ieyKej3fE/edit#
It was decided that the small and large video download URL's will not be added for this iteration.
=> Video metadata fields

ocw-course/ocw-studio.yaml
Fixes #69 
Adds topics field which was originally added in this PR https://github.com/mitodl/ocw-studio/issues/466
=> Add topics field

ocw-course/ocw-studio.yaml
Fixes #71 
Updates schema for information about files
=> Rename resourcetype, add file_type

ocw-course/ocw-studio.yaml
https://github.com/mitodl/ocw-hugo-projects/issues/45 
this PR adds a license dropdown to resource objects for courses created with the ocw-course schema
follow the steps in https://github.com/mitodl/ocw-studio/pull/601
=> add license

ocw-course/ocw-studio.yaml
Fixes #88 
Fixes #89 
- Adds term and level as string fields
- Change level to be a multiple choice select field
=> Adjust level, add term and year fields

ocw-course/ocw-studio.yaml
https://github.com/mitodl/ocw-studio/issues/870
This pr adds legacy_uid to the studio course config
Follow the steps in https://github.com/mitodl/ocw-studio/pull/874
=> legacy_uid

ocw-course/config.yaml
https://github.com/mitodl/ocw-hugo-themes/issues/300
This pr adds a config change to add a /course_data.json to the course home page
Follow the steps in https://github.com/mitodl/ocw-hugo-themes/pull/306
=> config for course_data.json

ocw-www/ocw-studio.yaml
closes #116 
This just adds a new markdown field to the 'resource collection' content type on ocw-www.
This is pretty straightforward, but it would be good to confirm that the schema is valid by copy-pasting into Studio.
=> add a markdown description field to the resource collection

ocw-www/ocw-studio.yaml
https://github.com/mitodl/ocw-hugo-projects/pull/140
I renamed the target content type but forgot to rename the _field_!
the change should make sense
=> small typo/oversight in the www config

ocw-www/ocw-studio.yaml
Closes #148 
Replaces a course collection's "Featured Courses" with a "Featured Course List"
Convert the ocw-www/ocw-studio-config.yml file to JSON and paste into the ocw-www starter config in studio.
Create some course lists if you don't have any already for ocw-www
Create/edit a course collection and check that you can select 1 course list to be the featured course list. All other fields should work as before.
=> For course collections, change featured courses to a featured course list

ocw-www/ocw-studio.yaml
Part 2 of issue https://github.com/mitodl/ocw-hugo-themes/issues/614
Changed name , label and folder of testimonials to stories
- In local ocw-studio copy the configuration in ocw-www starter or custom starter
- Verify testimonials has be changed to stories in ocw-www starter custom starter
=> renamed testimonials to stories

mit-fields/ocw-studio.yaml, ocw-course/ocw-studio.yaml, ocw-www/ocw-studio.yaml
https://github.com/mitodl/ocw-studio/issues/1277
Updates configs to accomodate `minimal=true` as default for markdown widget.
See https://github.com/mitodl/ocw-studio/pull/1350
=> update configs for minimal markdown editor by default

ocw-course/ocw-studio.yaml
Related to https://github.com/mitodl/ocw-studio/pull/1316 and https://github.com/mitodl/hq/discussions/1
Adds `site-url-format` to the ocw-studio config, which will be used to suggest a publish url for sites.
Copy the line into the ocw-course starter config in studio and follow the testing instructions for PR https://github.com/mitodl/ocw-studio/pull/1316
=> URL pattern for ocw-studio.yaml

ocw-course/ocw-studio.yaml
Closes #173 
- adds 'False' as default value for resources draft field
- Verify resources created with this config have an initial value for false for draft
=> added default value for resource

ocw-course/ocw-studio.yaml
Closes #196 
Adds a configuration for resource bundle.
- Use this configuration in studio and verify resource bundle can be created.
=> Added config for resource bundle

ocw-course/ocw-studio.yaml
This reverts commit 9fe2ed0bb5d057535339274cb83d39f052af0337.
N/A
Reverts a previous commit that breaks ocw-studio.
=> Revert "Added config for resource bundle (#198)"

ocw-course-v2/config-offline.yaml, ocw-course-v2/config.yaml, ocw-course-v2/ocw-studio.yaml, ocw-course/config-offline.yaml
Related to https://github.com/mitodl/ocw-hugo-themes/issues/308
This PR adds a `config-offline.yaml` file to the `ocw-course` project. It also adds a project called `ocw-course-v2` for the `course-v2` theme with an identical `ocw-studio.yaml` to `course` as well as `config.yaml` and `config-offline.yaml` files.  This ensures that in `ocw-studio` you can set a starter to either `ocw-course` or `ocw-course-v2` and use all of the online or offline pipelines and create and build sites.
This PR is tested as part of https://github.com/mitodl/ocw-hugo-themes/pull/832 and https://github.com/mitodl/ocw-studio/pull/1453. If everything checks out with those PR's, then this PR has been tested.
=> offline course site config

ocw-course-v2/ocw-studio.yaml, ocw-course/ocw-studio.yaml
Closes https://github.com/mitodl/ocw-hugo-projects/issues/220.
Adds "High School" as a level for courses.
Paste the contents of `ocw-course/ocw-studio.yaml` and `ocw-course-v2/ocw-studio.yaml` into the appropriate Website Starters in Django admin, create new courses using those starters, and verify that High School is now a level in the course metadata for each.
=> Adding High School as a level for courses

ocw-www/config-offline.yaml
Part of upgrading `Hugo` to latest version in `ocw-hugo-themes`
Testing instructions mentioned in this PR: https://github.com/mitodl/ocw-hugo-themes/pull/1512
=> Replace paginate with pagination.pagerSize
