- ocw-www/ocw-studio.yaml
Fixes https://github.com/mitodl/ocw-hugo-projects/issues/5
This PR fixes a number of issues:
- `name` property on collection items set to plurals to match `ocw-hugo-themes` so the `type` key is written out properly
- `lead_quote` corrected to `leadquote`
- `image_object` wrappers removed, as they create the object structure in the resulting front matter
- `body` added to notifications
- `subtitle` added to promos
- Create a new `WebsiteStarter` in `ocw-studio` RC Django admin
- Convert `ocw-www/ocw-studio.yaml` to JSON and paste it in the Config field for the starter
- Create a new `Website` using this starter
- Create one of each type of content, then hit the preview button
- Find the site's repo on https://github.mit.edu and look through the markdown
- Verify:
- The `type` properties in …
> ocw-www config updates and missing fields

- ocw-www/ocw-studio.yaml
Closes https://github.com/mitodl/ocw-hugo-projects/issues/7
In an effort to build `ocw-www` content generated by `ocw-studio`, images will no longer be uploaded directly into the `static` folder of the `ocw-www` github repo and instead will be uploaded to `ocw-studio`.  This PR adds a definition for a resource collection with support for extra metadata for images.  Relation widgets were also set on promos and testimonials filtering on the Image type resources.
- Convert the `ocw-www/ocw-studio.yaml` file to JSON, create a test `WebsiteStarter` in `ocw-studio` and paste our JSON in as the configuration
- Create a test `Website` using the `WebsiteStarter` we created
- Go to the "Resource" section and test uploading each type of resource
- Go to the "Promo" section and create a test promo, …
> resource definition and image relation widgets

- ocw-course/ocw-studio.yaml
- ocw-www/ocw-studio.yaml
This depends on https://github.com/mitodl/ocw-studio/pull/338
- Partially addresses #336 
- Adds `root-url-path` to `ocw-studio.yml` files
- Start up ocw-studio on the `mb/siteconfigpath` branch
- Convert each of the modified yaml files to JSON and create new `WebsiteStarter`s with the JSON as the site config.  The configs should validate.
- Create a new site with each starter and add a resource, uploading a file.  Check the filepath of the uploaded file, it should start with the `base-url` value specified in the site config if any, then the `Website.name` value: `<root-url-path>/<site_name>`
> Add root-url-path to ocw-studio.yaml files

- ocw-course/ocw-studio.yaml
Closes https://github.com/mitodl/ocw-hugo-projects/issues/12
In https://github.com/mitodl/ocw-hugo-projects/pull/4, we added an `ocw-studio` configuration for the `ocw-www` website.  This PR adds the `page` and `resource` collections to the `ocw-course` studio config as they exist in the `ocw-www` starter to the `ocw-course` starter to allow the uploading of resources and the creation of generic pages.
- Set up `ocw-studio` locally or use the RC instance for testing and log in with an admin user
- Add a `WebsiteStarter` in Django admin
- Convert `ocw-course/ocw-studio.yaml` to JSON and paste it into the configuration field for your new `WebsiteStarter` and then save it
- Verify that the config validates and the `WebsiteStarter` object is saved
> add basic pages and resources to courses

- .github/ISSUE_TEMPLATE/bug_template.md
- .github/ISSUE_TEMPLATE/feature_template.md
- .github/pull_request_template.md
N/A
This PR adds basic Github Issue / PR templates to this repo
No testing required, this just copies in Github templates used in other projects
> add standard github issue / PR templates

- ocw-course/ocw-studio.yaml
Closes https://github.com/mitodl/ocw-hugo-projects/issues/22
This PR adds the course title as a required field to the course metadata in the course starter.
- Convert `ocw-course/ocw-studio.yaml` to JSON and paste it into a starter in either a locally running instance of `ocw-studio` or on RC
- Create a Website using the new Website Starter you made and click on Metadata under settings
- Ensure that Course Title is displayed as a string field
> add course title

- ocw-course/ocw-studio.yaml
Fixes https://github.com/mitodl/ocw-hugo-projects/issues/30
This PR removes the max selection limitation on departments that was accidentally added in the initial PR.
- Convert `ocw-course/ocw-studio.yaml` to JSON
- In `ocw-studio`, create a `WebsiteStarter` using this JSON
- Create a `Website` using this starter
- Go to the Course Metadata section and add more than 2 department numbers and click save
- Verify that the metadata saved and there were no errors
> remove max selection limit on department numbers

- ocw-course/ocw-studio.yaml
Closes https://github.com/mitodl/ocw-hugo-projects/issues/24
This PR adds the course feature tags from `ocw-data-parser` (https://github.com/mitodl/ocw-data-parser/blob/2580dcaf52be4e2e0c1098be527bd19cfc8e7288/ocw_data_parser/course_feature_tags.py#L59-L101) as a multiple choice list to both the course metadata and course resources.  The tags you can set on a Resource have been edited to be singular rather than plural.  The tags are a simple list of strings and multiple can be associated with both resources and the course metadata.
- Paste the site config into a new Website Starter in your local instance of `ocw-studio` (or on RC). The Django admin field is equipped to handle yaml or json, and will be automatically converted to json if yaml is pasted in.
- Create a Website using this new …
> add course feature tags to resources and course metadata

- ocw-course/ocw-studio.yaml
Closes https://github.com/mitodl/ocw-hugo-projects/issues/25
This PR adds `primary_course_number` and `extra_course_numbers` as required string fields to the course site starter.  The `extra_course_numbers` field has traditionally been a list of strings in OCW, and for now we will simply be representing this with a comma separated string.  This has been noted in the label for the extra course numbers field, but in the future we should add validation or a `multiple: true` parameter to the string widget, or both.
- Paste the site config into a new Website Starter in your local instance of `ocw-studio` (or on RC). The Django admin field is equipped to handle yaml or json, and will be automatically converted to json if yaml is pasted in.
- Create a Website using this new Website Starter
- Go …
> add course numbers

- ocw-course/ocw-studio.yaml
N/A
Extra course numbers were accidentally set as a required field when they shouldn't be.  This PR sets the field as not required.
- Paste the site config into a new Website Starter in your local instance of `ocw-studio` (or on RC). The Django admin field is equipped to handle yaml or json, and will be automatically converted to json if yaml is pasted in.
- Create a Website using this new Website Starter
- Go to Settings -> Metadata and make sure Extra Course Numbers is blank
- Verify that you can save the metadata
> mark extra_course_numbers as not required

- .gitignore
- ocw-www/ocw-studio.yaml
N/A
Adds a nav menu to the site config so that published course sites can have a Hugo menu configured
- Paste the site config into a new Website Starter in your local instance of `ocw-studio` (or on RC). The Django admin field is equipped to handle yaml or json, and will be automatically converted to json if yaml is pasted in.
- Create a Website using this new Website Starter, and create a few pages. 
- Go to settings > menu, add those pages and some external links to the menu, and save
- Check your exported site in Github and navigate to `/config/menu-sidenav.yml`. The content of that file should be a valid Hugo menu format, and should match the menu you arranged in OCWS
> Added nav menu to site config

- ocw-course/ocw-studio.yaml
Closes https://github.com/mitodl/ocw-hugo-projects/issues/51
When importing courses in `ocw-studio` using `import_ocw_course_sites`, the `type` on course sections is set to the constant value of `CONTENT_TYPE_PAGE` which at the time of writing is `page`. This PR changes the `name` property of the Pages collection in the course starter from `pages` to `page` so that when courses are imported and assigned the starter from this repo, everything lines up properly.
- Spin up a local instance of `ocw-studio` or use RC for the steps below, and make sure you have AWS credentials for RC set in your env if you are using a local instance of studio
- Copy and paste the contents of `ocw-course/ocw-studio.yaml` into a `WebsiteStarter` in OCW Studio's Django admin interface
- On the OCW Studio instance, …
> page not pages

- ocw-course/ocw-studio.yaml
Closes https://github.com/mitodl/ocw-hugo-projects/issues/41
This PR adds the course description markdown field to the course metadata in the course starter
- Copy and paste `ocw-course/ocw-studio.yaml` into a `WebsiteStarter` in a locally running instance of `ocw-studio` (or on RC)
- Create a new site using this starter and go to the Course Metadata section
- Enter some data into the course description and fill out the other required fields, make make sure you can save
> add markdown course description to metadata

- ocw-course/ocw-studio.yaml
Closes https://github.com/mitodl/ocw-hugo-projects/issues/43
This PR adds a navigation menu widget to the course starter.  It is configured to produce a menu that will be compatible with the course theme in `ocw-hugo-themes`
- Copy and paste the contents of `ocw-course/ocw-studio.yaml` into a `WebsiteStarter` config in either your locally running instance of `ocw-studio` or on RC
- Create a `Website` using the `WebsiteStarter` you created above
- Go to the Menu section and add a few menu items and verify you can save
> add nav menu widget to course starter

- ocw-www/ocw-studio.yaml
Closes https://github.com/mitodl/ocw-hugo-projects/issues/55
This PR simply changes "-" to "_" in the name property of the Image ALT field.
- Load the course starter (`ocw-course/ocw-studio.yaml`) into an instance of `ocw-studio` and create a site
- Add at least one image resource to the site and specify Image ALT
- Publish this site and download the published markdown
- Clone `ocw-hugo-themes` and add a layout at `course/layouts/resource/single.html` with the following content:
```
```
- Try and render the site using `hugo --themesDir /path/to/ocw-hugo-themes --config /path/to/ocw-hugo-projects/ocw-course/config.yaml`
> use underscore instead of hyphen in image_alt

- ocw-www/config.yaml
Closes https://github.com/mitodl/ocw-hugo-projects/issues/63
In https://github.com/mitodl/ocw-hugo-themes/pull/167, we added JSON layouts to the `base-theme` and `www` themes.  These define a base JSON file for rendering a static API as well as a layout for instructor JSON API responses.  This PR adds the necessary configuration to `ocw-www/config.yaml` to support rendering JSON files in the Hugo output
- Clone `ocw-hugo-themes` on the `cg/instructors-static-api` branch
- Read the readme if you've never worked with `ocw-hugo-themes` before
- Spin up the webpack dev server locally by running `npm run start:site:webpack`
- Clone https://github.com/mitodl/ocw-hugo-projects on this PR branch
- Clone https://github.mit.edu/ocw-content-rc/ocw-www/ and open a terminal in the resulting folder
- …
> add json media types and outputs

- ocw-course/ocw-studio.yaml
N/A
Fixes a bug where video metadata was always overwriting image metadata because of a shared name.
In ocw-studio, update the site config to match the changes here.
Create an image resource and a video resource, fill out metadata fields for each, and save. Reload each resource and verify the field values were saved.
> Separate metadata sections for videos, images

- ocw-course/ocw-studio.yaml
https://github.com/mitodl/ocw-hugo-projects/issues/58
This pr replaces course_feature_tags with learning_resource_type in the ocw-course starter
1) Paste the site config into a new Website Starter in your local instance of ocw-studio
2) Create a Website using this new Website Starter
3) Create a resource for the website and set "Learning Resource Type". Verify that you can save the resource
> course_feature_tags->learningResourceType

- ocw-course/ocw-studio.yaml
Related to https://github.com/mitodl/ocw-studio/pull/501
Adds `attach: "resource"` so the resource picker will be active for content body
> Add attach:resource

- ocw-www/ocw-studio.yaml
Related to https://github.com/mitodl/ocw-studio/pull/600
New instructors have a filename assigned to them using the instructor title. However we need to use the uuid as the filename so that ocw-hugo-themes can fetch instructor data when the website is built. This communicates that the `text_id` which contains the uuid should be used when creating the filename.
> Add slug field for instructor

- ocw-course/ocw-studio.yaml
Closes https://github.com/mitodl/ocw-hugo-projects/issues/90
The new design for video galleries includes a description above the video cards.  This PR adds a field to the Video Gallery configuration in the `ocw-course` starter to add a description markdown field to the video gallery pages.
- Spin up a local instance of [`ocw-studio`](https://github.com/mitodl/ocw-studio) and ensure you are setup to publish sites to a test Github organization and Google drive integration is enabled
- Visit http://localhost:8043/admin and create a new `WebsiteStarter` object and paste in the contents of `ocw-course/ocw-studio.yaml`
- Visit http://localhost:8043/sites and create a new site using the starter you just created
- Visit the metadata section and fill in the required fields
- Visit the Resources …
> add a description field to video galleries

- ocw-course/config.yaml
Closes https://github.com/mitodl/ocw-hugo-projects/issues/95
As of the time of writing, the sites at https://ocwnext-rc.odl.mit.edu and https://ocwnext.odl.mit.edu are built using a custom EC2 server and a monolithic bash script that pulls down all the legacy OCW course data from S3 and processes it with [`ocw-to-hugo`](https://github.com/mitodl/ocw-to-hugo).  Then, each of those courses are built using [`ocw-hugo-themes`](https://github.com/mitodl/ocw-hugo-themes) along with the Hugo config from this repo located at `ocw-course/config.yaml`.
In https://github.com/mitodl/ocw-hugo-themes/pull/186, we changed [`ocw-hugo-themes`](https://github.com/mitodl/ocw-hugo-themes) to source instructors displayed under course info from a static API, defined in `STATIC_API_URL`.  This static API is …
> ignore errors getting json during course builds

- ocw-course/config.yaml
- ocw-www/config.yaml
Closes https://github.com/mitodl/ocw-hugo-projects/issues/105
In Hugo 0.91, there has been an update to the default security configuration:
https://gohugo.io/about/security-model/#security-policy
This is a breaking change that throws a hard error whenever Hugo tries to access an environment variable that isn't explicitly allowed.  This PR adds the env variables that we use in `ocw-hugo-themes` explicitly to the Hugo configurations stored in this repo.
- Clone `ocw-hugo-themes`
- Clone `ocw-hugo-projects`
- Clone https://github.mit.edu/ocw-content-rc/ocw-www
- Run `npm run build -- /path/to/ocw-www /path/to/ocw-hugo-projects/ocw-www/config.yaml`
- Ensure that the build completes with no errors
> hugo 0.91 security updates

- ocw-www/ocw-studio.yaml
closes #101
related to https://github.com/mitodl/ocw-studio/issues/885 
🚧 **blocked until https://github.com/mitodl/ocw-studio/pull/888 merges** 🚧 
This PR adds a new content type to the ocw-www config file which defines a course collection using the new `website-collection` widget type introduced in https://github.com/mitodl/ocw-studio/pull/888.
After https://github.com/mitodl/ocw-studio/pull/888 merges you should be able to use this ocw-www config in your dev environment to see a UI that lets you create collections of websites.
> add config for course collections to ocw-www

- ocw-course/config.yaml
for https://github.com/mitodl/ocw-hugo-themes/issues/279
This adds a `content_map` output type
it can be tested as part of testing https://github.com/mitodl/ocw-hugo-themes/pull/400
> add output type for content map, add that to the homepage

- ocw-course/ocw-studio.yaml
Closes https://github.com/mitodl/ocw-hugo-projects/issues/115
- Adds Learning Resource type: `Instructor Insights` for courses and resources
- Go to the admin (django admin) site of `ocw-studio`: either setup it up locally or use RC.
- Add a new `WebsiteStarter`
- Paste the configuration in `ocw-course/ocw-studio.yaml` into the config field for this new WebsiteStarter and then save it.
- Verify that the config is validated and `WebsiteStarter` is successfully saved.
- Create a new site with this starter
- Go to site's metadata and resources and verify that Learning Resource type has `Instructor Insights`
> feat: learning resource type: instructor insights added

- ocw-course/ocw-studio.yaml
- ocw-www/ocw-studio.yaml
The "link" and "embed" keys control what types of content can be linked/embedded in OCW Studio's markdown editor.
Adds link/embed keys for controlling which types of content can be linked/embedded in Studio's markdown editor.
See https://github.com/mitodl/ocw-studio/pull/1055
> remove attach; add link + embed

- ocw-course/ocw-studio.yaml
Fixes a bug from https://github.com/mitodl/ocw-hugo-projects/pull/128
Removes "Pages" from the embed list
Use the updated config in OCW studio and check that pages no longer appear in the embed list.
> do not allow embedding pages

- ocw-course/ocw-studio.yaml
- ocw-www/ocw-studio.yaml
Closes https://github.com/mitodl/ocw-studio/issues/933
This PR adds a boolean `draft` field to items in the `Content` category in both the `ocw-www` and `ocw-course` starter configurations, defaulting to false.  When set to true, this will automatically set `draft: true` in the front matter of any content being published, telling Hugo to not render the page or any JSON data.
- Spin up a local instance of [`ocw-studio`](https://github.com/mitodl/ocw-studio), making sure you follow the instructions to set up your own Github organization for testing
- Create the `ocw-www` and `ocw-course` starters if you don't have them already and update their configuration with the ones from this branch
- Create a test site or open an existing one
- Create two test pages, one with `draft` set to `false`, …
> add draft to the types of content that need it

- ocw-course/ocw-studio.yaml
- ocw-www/ocw-studio.yaml
N/A
In https://github.com/mitodl/ocw-hugo-projects/pull/125, we added the Draft setting for all types of content that support it.  `help_text` was mistakenly set on these properties to add a description to the UI about the field, when the field it should have gone in is simply `help`.  This PR corrects that by moving the help text to `help`.
Make sure you can copy & paste `ocw-course/ocw-studio.yml` and `ocw-www/ocw-studio.yml` into `ocw-studio`'s Django admin in the configuration field for a `WebsiteStarter` without error.  Go to a site using this starter afterward and make sure you see "Enable this setting to prevent publishing in production" under the draft settings.
> help not help_text

- ocw-course/ocw-studio.yaml
Makes video_gallery markdown bodies editable 
I included embedding/linking because that seems desirable?
1. Paste the new config into `ocw-course` website starter in local admin panel
2. Check that the markdown body shows up at http://chris.ocw-studio.odl.local:8043/sites/res-9-003-brains-minds-and-machines-summer-course-summer-2015/type/video_gallery/edit/e1619dcf-4933-8ee6-8458-d20fd651289a/ ... but with your version of `chris.ocw...`.
3. Edit the markdown and save
> make video_gallery markdown body editable

- ocw-www/ocw-studio.yaml
closes #142 
This PR adds configuration for a course collection gallery content type. This is basically a "collection of collections," and will render w/ a description and then the collections which have been added to it.
The idea is that this will be a good way to represent some of the more complicated collections that currently exist on production OCW, where there are different sections and whatnot. Basically, course authors would author each of those sections as a separate course collection, with a description and a list of courses, and then add them to a course collection gallery in the desired order.
You could paste this config into Studio and make sure it works properly.
> add configuration for course list, collection

- ocw-course/ocw-studio.yaml
Closes https://github.com/mitodl/ocw-hugo-projects/issues/153
This PR adds markdown body editing to resources.  The body will be used to write descriptions for videos and other resources to be displayed on the resource page rendered by Hugo during the site build.
- Spin up a local instance of [`ocw-studio`](https://github.com/mitodl/ocw-studio) and ensure you have a test Github org set up as described in the readme
- Create a new `WebsiteStarter` or update an existing one with the contents of `ocw-course/ocw-studio.yaml` from this branch
- Choose one of these 3 options:
- Make sure your `ocw-studio` is set up with Google Drive credentials from RC and upload a video to your course, then sync
- Import a course using `import_ocw_course_sites` that has video resources
- Go into Django admin …
> add body text editing to resources

- ocw-course/ocw-studio.yaml
Part of https://github.com/mitodl/ocw-hugo-projects/issues/156
Closes https://github.com/mitodl/ocw-hugo-projects/issues/152
Currently, YouTube descriptions are sourced from the `description` field on a resource, which is a markdown field.  This isn't ideal for a couple reasons; one being that the resource description doesn't necessarily match the description desired for YouTube but also the YouTube description does not even support markdown.  This PR adds a new raw text field to the `ocw-course` starter explicitly for YouTube descriptions under `video_metadata.youtube_description`.  Help text was also added on the `title` property, `video_metadata` and `video_files` sections stating that those fields will be published to YouTube.
- Spin up a local instance of …
> add youtube description field and help text

- ocw-www/ocw-studio.yaml
Closes https://github.com/mitodl/ocw-hugo-projects/issues/147
- Sets `Required=true` for promo images
- Copy the config in `ocw-www/ocw-studio.yaml`.
- Go to `ocw-studio`, either RC or your local setup.
- In `ocw-studio` admin: Paste this config in any website starter for which there's a course.
- In `ocw-studio` sites: Open the course whose starter config has been updated.
- Try adding a new promo and verify that now promo image is required.
> promo image required

- ocw-www/ocw-studio.yaml
Closes https://github.com/mitodl/ocw-hugo-projects/issues/160
- Adds `resource embed` in ocw-www studio config 
- Adds `resource` and `page` link in ocw-www studio config
- Changes `name: filetype` to `name: resourcetype` for resources in in ocw-www studio config
- Checkout this branch
- Copy the config
- Either in studio RC or in studio local setup, paste this config in the starter of `ocw-www`
- Go to `ocw-www` in `studio/sites` and add/edit a page 
- Verify that `Embed Resource` button is now there in editor.
- Verify that all the resources are being shown when you try to embed a resource.
- Verify that resource and page are there when you add a link
> feat: embed resource added for ocw www

- ocw-course/ocw-studio.yaml
Closes https://github.com/mitodl/ocw-hugo-projects/issues/47
In https://github.com/mitodl/ocw-hugo-themes/pull/270, we set up the course theme to pass image captions and credits through `.RenderString` so they would be processed as markdown.  This PR changes the image metadata caption and credit fields in the `ocw-course` starter to use the markdown widget instead of simply being text.
- Copy and paste the config into your local instance of `ocw-studio`
- Find or create an image resource in a site and edit it
- Put some text into the caption and credit fields and make sure to use components that would render as markdown like title, basic links, italics, bold, etc.
- Publish your site and make sure that markdown is rendered in the front matter for this resources in the proper place
> use markdown widget on captions and credits

- mit-fields/config.yaml
- mit-fields/ocw-studio.yaml
Closes https://github.com/mitodl/ocw-hugo-projects/issues/167
This PR adds the new `mit-fields` starter definition and Hugo config.  It allows creation of websites in `ocw-studio` that will utilize the `fields` theme in `ocw-hugo-themes`.
- This starter has already been manually added to `ocw-studio-rc` with the id `mit-fields`
- Create a site using the `mit-fields` starter
- Add some Subfields and add courses and descriptions to them
- Go to the images section and upload a cover image
- Visit the Fields section and fill out the data, making sure you set a featured course list as well as adding multiple Subfields as well as set the cover image
- Publish your site and view it once publishing is complete, making sure everything looks as expected based on the screenshots in this PR: …
> add mit-fields starter

- ocw-course/ocw-studio.yaml
closes https://github.com/mitodl/ocw-studio/issues/1254
Makes legacy_uid uneditable
This should be tested with https://github.com/mitodl/ocw-studio/pull/1304
Update the  ocw-course starter on https://ocw-studio-rc.odl.mit.edu to the starter in this pr. 
Delete the legacy_uid from the metadata for an imported course through the admin ui. 
Run `heroku run python manage.py -a ocw-studio-rc import_ocw_course_sites -b ocw-to-hugo-output-qa --filter <course-slug>` to verify that the legacy_uid field is repopulated in the metadata and set to what it was before. 
Go to the metadata page in the course editing ui. Verify that legacy uid is not an editable field
> make legacy uid hidden

- mit-fields/config.yaml
- ocw-course/config.yaml
- ocw-www/config.yaml
Related to https://github.com/mitodl/ocw-hugo-themes/issues/673
This PR adds `SITEMAP_DOMAIN` to the list of allowed env variables that can be utilized in the `ocw-course` and `ocw-www` Hugo configurations.  This is necessary for coming changes to the sitemap layouts in `ocw-hugo-themes` that will construct a fully qualified URL for use in the url locations contained within.
This PR should be tested in conjunction with https://github.com/mitodl/ocw-hugo-themes/pull/674
> add SITEMAP_DOMAIN to the list of allowed env variables

- mit-fields/config.yaml
- ocw-course/config.yaml
- ocw-www/config.yaml
Related to https://github.com/mitodl/ocw-hugo-themes/issues/673
This PR adds a new `outputFormat` definition to the `ocw-www` Hugo configuration called `sitemapIndex` and assigns it to the `home` kind.  What this does is ensure that when an xml template is defined for the `home` page in a site using the `ocw-www` theme, it will be used to generate a `sitemap_index.xml` file.  This file acts as an index for large sites with multiple sitemaps.  More info can be found [here](https://developers.google.com/search/docs/advanced/sitemaps/large-sitemaps).
Tested as part of https://github.com/mitodl/ocw-hugo-themes/pull/679
> add sitemap_index outputFormat to ocw-www

- ocw-www/config.yaml
Closes https://github.com/mitodl/ocw-hugo-projects/issues/178
In https://github.com/mitodl/ocw-hugo-projects/pull/176, a custom `outputFormat` was defined for the `ocw-www` sitemap, and it was assigned to the home page.  This had the side effect of causing the home template to only generate XML for the sitemap, and it stopped generating HTML for the home page.  This PR adds back the default output formats explicitly, because apparently that's required.
- Clone `ocw-hugo-themes` and configure it to point to a locally cloned copy of this repo using `WWW_HUGO_CONFIG_PATH`
- Clone `ocw-www` from the `mitocwcontent` org at github.mit.edu and point to that with `WWW_CONTENT_PATH`. Then spin up `ocw-www` with `npm run start:www`
- Verify that you can visit the home page at http://localhost:3000
> explicitly add back default output formats for the ocw-www home page

- ocw-course/ocw-studio.yaml
Closes https://github.com/mitodl/ocw-hugo-projects/issues/185
In https://github.com/mitodl/ocw-hugo-projects/pull/155, we added editing of the markdown body to resources, as it was necessary for legacy courses where multiple legacy description fields are combined into the markdown body of the resource.  This PR improves upon that a bit, by configuring `ocw-studio` so that the field labeled "Description" writes its content to the markdown body, unifying where the description is stored.  The markdown editor was set to `minimal: true` and linking of pages and other resources is allowed.  This is now possible because https://github.com/mitodl/ocw-studio/pull/1364 has been merged.
- Spin up `ocw-studio` locally on `master`
- Copy and paste the configuration at `course/ocw-studio.yaml` into …
> store course resource description in markdown body

- ocw-course/ocw-studio.yaml
- ocw-www/ocw-studio.yaml
Part of https://github.com/mitodl/ocw-hugo-themes/issues/725
This PR adds new `metadata_description` and `metadata_keywords` fields to the `page` types of content in `ocw-www` and `ocw-course`.  These values will be written into `meta` tags with the `name` "Description" and "Keywords" so they can be read by search engines for purposes of indexing.
- Run an instance of `ocw-studio` locally
- Copy and paste the `ocw-www/ocw-studio.yaml` and `ocw-course/ocw-studio.yaml` files into the appropriate starter in your local instance of `ocw-studio` in Django admin
- Create a page in both types of sites, fill out the Metadata Description and Keywords fields and publish your sites to your test org
- Verify that the description that you wrote shows up in the front matter under `metadata_description` …
> add metadata_description and metadata_keywords fields to pages

- ocw-course/ocw-studio.yaml
- ocw-www/ocw-studio.yaml
Follow up to https://github.com/mitodl/ocw-hugo-projects/pull/190
Closes https://github.com/mitodl/ocw-hugo-projects/issues/193
In https://github.com/mitodl/ocw-hugo-projects/pull/190, we added plain text description fields to pages in both `ocw-course` and `ocw-www`.  The widget property on these was set to `string` when it should have been `text`, as these descriptions can be long and require multi-line input.  This PR does just that, changes the widgets on them to `text`.
- Run `ocw-studio` manually
- Copy and paste `ocw-www/ocw-studio.yaml` and `ocw-course/ocw-studio.yaml` into their appropriate starters in your local `ocw-studio`'s Django admin interface
- Open an existing course or create a new one and open a page or create a new one
- Verify that the description field is now a …
> plain text description fields should be text and not string

- RELEASE.rst
no issue, I just noticed that the release notes were misleading
Corrects the release notes to remove "add ... metadata_keywords fields to pages"
I hope this doesn't mess up Doof too much.
> fix: we did not add a metadata_keywords field to pages

- ocw-course/config.yaml
- No ticket :)
- Adds `learning_resource_type` [taxonomy](https://gohugo.io/content-management/taxonomies/).
- Checkout this branch
- Make sure `COURSE_HUGO_CONFIG_PATH` is set in `ocw-hugo-themes` env.
- For `ocw-hugo-themes`, checkout to the branch of this PR https://github.com/mitodl/ocw-hugo-themes/pull/753.
- Build any course locally which has learning resource types.
- Go to `http://localhost:3000/resources/` and verify that all the resources are being rendered properly
- Verify that when you click `See All`, all resources for a particular type are rendered properly.
- Please read [this thread](https://github.com/mitodl/hq/discussions/92#discussioncomment-2954821) for context/details.
> feat: learning_resource_type taxonomy added

- ocw-course/config.yaml
No ticket :) 
- Defines permalink for `learning_resource_types` taxonomy so `/resources` is used instead of `/learning_resource_types`
- Checkout the branch of this PR: https://github.com/mitodl/ocw-hugo-themes/pull/753
- Build any course which has more than 10 resources for any particular type
- Go to `/resources`
- Click `See All`
- Verify that you're redirected to `/resources/type` instead of `/learning_resource_types/type`
https://github.com/mitodl/ocw-hugo-themes/pull/753
> permalink added for learning_resource_types

- ocw-course/ocw-studio.yaml
Closes #196 
- Adds resource bundle to config
- Does not add resource bundle to link
- Use this config on ocw-studio
- Verify you are able to create resource bundles
Resource list was added in PR #196 in course config. However it was not added in TABS in ocw-studio which caused problems in rendering pages thus it was reverted in PR #206. Following PR https://github.com/mitodl/ocw-studio/pull/1411 for ocw-studio adds checks to prevent this issue.
This PR adds resource list back to ocw-studio config
> Added resource list to to course config which was reverted in PR #206

- ocw-course/config.yaml
- ocw-www/config.yaml
Closes https://github.com/mitodl/ocw-hugo-projects/issues/201
According to https://gohugo.io/hugo-modules/theme-components, Hugo's lookup order goes through the themes defined in your project from left to right and the file with the same name found in the "leftmost" theme wins.  In our Hugo configs, our `theme` section has `base-theme` first in both `ocw-www` and `ocw-course`.  In order to be able to override layouts in the base theme, we need `base-theme` to be last.
- Check out `ocw-hugo-projects` and `ocw-hugo-themes` on the `main` branches as well as any course from `mitocwcontent`
- In the `.env` of your `ocw-hugo-themes` repo, make sure you have: 
```
COURSE_HUGO_CONFIG_PATH=/home/gumaerc/Code/ocw-hugo-projects/ocw-course/config.yaml
COURSE_CONTENT_PATH=/path/to/mitocwcontent/ …
```
> change order of theme inheritance

- mit-fields/config.yaml
- ocw-course-v2/config-offline.yaml
- ocw-course-v2/config.yaml
- ocw-course/config-offline.yaml
- ocw-course/config.yaml
- ocw-www/config.yaml
Related to https://github.com/mitodl/ocw-hugo-themes/pull/903 & https://github.com/mitodl/ocw-studio/pull/1548
- Adds `SENTRY_DSN` to the list of allowed env variables in all `config.yaml` and `config-offline.yaml`
> SENTRY_DSN added to the list of env variables

- mit-fields/config.yaml
- ocw-course-v2/config-offline.yaml
- ocw-course-v2/config.yaml
- ocw-course/config-offline.yaml
- ocw-course/config.yaml
- ocw-www/config.yaml
https://github.com/mitodl/ocw-hugo-themes/issues/919
Whitelists the WEBPACK_PORT environment variable.
1. Checkout this branch of ocw-hugo-projects and [cc/ci3](https://github.com/mitodl/ocw-hugo-themes/tree/cc/ci3) of ocw-hugo-themes.
2. Set ocw-hugo-themes env var `WEBPACK_PORT` to some unused port, e.g., 4567
3. run `yarn start:course`; check that the course loads webpack assets.
4. Check that http://localhost:4567/static/css/main.css loads a css file, replacing the port number with whatever you used 
5. repeat with `yarn start:www`
> whitelist webpack_port

- ocw-course-v2/config-offline.yaml
- ocw-course-v2/config.yaml
Prerequisite for https://github.com/mitodl/ocw-hugo-themes/issues/937
This PR adds two things to the `course-v2` configs:
- Allows the `HEAD` verb in addition to `GET` in the `security.http` configuration so that `resources.GetRemote` is allowed to make `HEAD` requests
- Adds `application/zip` as a supported `mediaType` so ZIP files can be fetched with `resources.GetRemote`
This will be tested as part of
> allow HEAD verb and download of zip files

- mit-fields/config.yaml
- ocw-course-v2/config-offline.yaml
- ocw-course-v2/config.yaml
- ocw-course/config-offline.yaml
- ocw-course/config.yaml
- ocw-www/config.yaml
This PR whitelists `WEBPACK_HOST` environment variable for Hugo, which is introduced in https://github.com/mitodl/ocw-hugo-themes/pull/964. See that PR for more context.
Follow the steps in https://github.com/mitodl/ocw-hugo-themes/pull/964.
> whitelist webpack_host env var

- ocw-course-v2/config-offline.yaml
- ocw-course-v2/config.yaml
Closes https://github.com/mitodl/ocw-hugo-themes/issues/972
In https://github.com/mitodl/ocw-hugo-projects/pull/227, a change was inadvertently committed that set the default `baseUrl` setting in the `ocw-course-v2` starter's Hugo config to `http://localhost:3000/`. This causes `webpack_url.html` in `ocw-hugo-themes` to become confused when rendering the Netlify deploy previews, because `site.IsServer` will evalute to false and `site.BaseURL` is not blank. This causes the theme to try and use `site_root_url.html` to build the base url, resulting in a URL like `http://:/static/js/main.175c9.js`. This PR changes that back to `/` by default.
The real test as to whether or not this fixes the deploy preview will be after it's merged and deploy previews for active PR's in `ocw-hugo-themes` are …
> set default baseUrl in course-v2 back to /

- ocw-www/ocw-studio.yaml
Closes #241 
- Adds a new setting category which can be used to sort promos.
- Use this config to generate a ocw-www site in ocw-studio
- Add promos
- Verify a new setting call `HomePage` is shown
- Open HomePage setting and sort promos
- Publish course locally
- Verify a homepage.yml is produced
As per the latest [comment](https://github.com/mitodl/ocw-hugo-projects/issues/183#issuecomment-1382371103) by @ChristopherChudzicki , The feature to sort promos should be moved into  **Setting category** of ocw-studio. To handle this change a new setting called `HomePage` has been added in ocw-www stuidio config
> Added homepage settings in ocw-www studio config

- ocw-course-v2/config-offline.yaml
- ocw-www/config-offline.yaml
https://github.com/mitodl/ocw-hugo-themes/issues/1111
This PR adds a `config-offline.yaml` for the `ocw-www` project, to be used with the `www-offline` theme in `ocw-hugo-themes`. This config disables all output formats aside from HTML for the home page, sets `relativeURLs` and `uglyurls` to true and uses `disableKinds` to prevent the rendering of any content not relevant to this config's use case: using the `www-offline` theme to render a root level index of offline sites for use with OCW mirror drives. You may also notice that both this config and the `config-offline` in `ocw-course-v2` now first import `base-offline`, a theme added in https://github.com/mitodl/ocw-hugo-themes/pull/1113 that consolidates some of the common partials used between the offline Hugo sites into one place. …
> ocw-www offline config

- ocw-course-v2/ocw-studio.yaml
https://github.com/mitodl/hq/issues/980
This PR adds `archive_url` as a field under `video_files` with `widget: hidden`. The `archive_url` field only exists on legacy courses imported through [`ocw-to-hugo`](https://github.com/mitodl/ocw-to-hugo), and stores a URL to a video stored on archive.org. When `ocw-studio` uses the `ocw-course-v2` starter config as it is currently without this field defined, it will remove data in this field because it is not defined in the config. Defining the field as `hidden` prevents the field from showing up in the UI, but also prevents it from being clobbered by saving video objects.
- Spin up [`ocw-studio`](https://github.com/mitodl/ocw-studio) locally. You will need a recent database restore and be set up for publishing courses locally.
- Visit Django …
> add archive_url as a hidden field in video_files

- ocw-course-v2/ocw-studio.yaml
- ocw-www/ocw-studio.yaml
Closes https://github.com/mitodl/hq/issues/1680
Adds a file_size field to the resource collection config.
I've kept `widget: hidden` because we don't have a requirement for displaying the field on studio yet.
This field is not used anywhere at this time. We just need to ensure existing functionality does not break.
1. Navigate to your local clone of `ocw-hugo-projects`. And checkout `hussaintaj/1680-file-size` branch.
2. Navigate to your local setup of `ocw-studio` and checkout `master`.
3. In your studio's env file set `OCW_HUGO_PROJECTS_BRANCH="hussaintaj/1680-file-size"`
4. Start/Restart OCW Studio.
5. Run
```
docker-compose exec web ./manage.py override_site_config -s ocw-course-v2 -c path/to/ocw-hugo-projects/ocw-course-v2/ocw-studio.yaml
docker-compose exec web ./manage.py …
```
> feat: add file_size field

- ocw-course-v2/ocw-studio.yaml
Closes https://github.com/mitodl/hq/issues/2062
Adds a new "Recitation Notes" learning resource type to both the course metadata and the Edit Resource drawer.
Spin up local OCW-Studio, replace the website starter for ocw-course with the ocw-studio.yaml file modified in this PR. Check that "Recitation Notes" is now an option both in the course metadata and in the Edit Resource drawer under "Learning Resource Types".
> Add Recitation Notes as Learning Resource Type

- ocw-course-v2/ocw-studio.yaml
Closes https://github.com/mitodl/hq/issues/2759
This PR updates the studio configuration which enables the user to edit the `archive_url` field in video resources.
We will use Studio to test these configurations.
1. Navigate to your local `ocw-hugo-projects` directory.
2. Check out the branch `hussaintaj/2759-archive-url`.
3. Copy the contents of the file `ocw-course-v2/ocw-studio.yaml`. 
4. Navigate to your local `ocw-studio` directory.
5. Paste the contents you copied into `localdev/configs/default-course-config.yml`.
6. Start Studio i.e. `docker-compose up`.
7. Run
```sh
docker-compose exec web ./manage.py override_site_config -s ocw-course-v2 -c localdev/configs/default-course-config.yml
```
8. Open a course with video resources.
9. Open a video resource.
10. Expect the edit form of …
> feat(config): add form widget for archive_url

- ocw-course-v2/ocw-studio.yaml
https://github.com/mitodl/hq/issues/3175
Changes "Non Credit" to "Non-Credit" in the course metadata.
1. Checkout to this branch
2. Start OCW Studio locally. 
3. Copy the contents of `ocw-course-v2/ocw-studio.yaml` from this branch into the `ocw-course-v2` Website Starter config in Django admin. 
4. Then, navigate to http://localhost:8043/sites, select any course site, and click on Metadata under Settings. Verify that you see `Non-Credit` instead of `Non Credit`.
> Fix Level Non-Credit in Course Metadata

- ocw-course-v2/ocw-studio.yaml
N/A
This PR fixes the labels of existing licenses. This does not impact existing data. Only the Studio UI is affected.
1. Navigate to your local `ocw-studio` projects.
2. Add the following in your `.env` file.
```
GITHUB_WEBHOOK_BRANCH=hussaintaj/license-all-rights-reserved
```
3. Start/Restart Studio.
4. Run the following command in the shell.
```
docker-compose exec web ./manage.py import_website_starters https://github.com/mitodl/ocw-hugo-projects
```
5. Open any resource in the Studio UI.
6. Observe the license field.
7. Expect there to be no `-` between `CC` and the license name.
Originated from https://github.com/mitodl/ocw-hugo-projects/pull/271#discussion_r1461855581
> fix: license labels

- ocw-course-v2/ocw-studio.yaml
Relates to https://github.com/mitodl/hq/issues/3358
Required for https://github.com/mitodl/ocw-studio/pull/2130
Studio uses `WebsiteContent.title` instead of `WebsiteContent.metadata.title`. This PR removes the title field from the metadata because it remains unused and might cause confusion for future development.
1. Checkout branch `hussaintaj/remove-redundant-field` in your local clone of `ocw-hugo-projects`.
2. Navigate to your local `ocw-studio` project.
3. Replace the contents of `ocw-studio/localdev/configs/default-course-config.yml` with the content of `ocw-hugo-projects/ocw-course-v2/ocw-studio.yaml`.
3. Run
```sh
docker compose exec web ./manage.py override_site_config -c localdev/configs/default-course-config.yml -s ocw-course-v2
```
6. Open [Studio](http://localhost:8043).
7. …
> refactor(config): remove unused `title` field from external-resource

- .pre-commit-config.yaml
- ocw-course-v2/ocw-studio.yaml
Closes https://github.com/mitodl/hq/issues/4065
This PR adds a help text to the title. The title is a required field and is not required to be defined, but it has to be defined to add the help text.
This PR also adds a new license option `BY CC-SA` and changes default for external resources as requested in https://github.com/mitodl/hq/issues/4065.
1. Checkout branch `hussaintaj/external-resource-title-help-text` in your local clone of `ocw-hugo-projects`.
2. Navigate to your local `ocw-studio` project.
3. Replace the contents of `ocw-studio/localdev/configs/default-course-config.yml` with the content of `ocw-hugo-projects/ocw-course-v2/ocw-studio.yaml`.
4. Run
```sh
docker compose exec web ./manage.py override_site_config -c localdev/configs/default-course-config.yml -s ocw-course-v2
``` …
> config(course): add title update license fields

- ocw-www/ocw-studio.yaml
https://github.com/mitodl/hq/issues/3855
Relevant PR: https://github.com/mitodl/ocw-hugo-themes/pull/1397
Adds functionality to link and embed resources in `ocw-www `course lists and course collections.
One of the ways to test this would be:
1. Checkout to this branch
2. Use `OCW_HUGO_THEMES_BRANCH=ibrahim/3855/render-body-in-course-collection` in ocw-studio .env
3. Spin up `ocw-studio`
4. Update pipelines:
i. `docker-compose exec web ./manage.py upsert_theme_assets_pipeline`
ii. `docker-compose exec web ./manage.py backpopulate_pipelines --filter ocw-www`
5. Open concourse interface: http://concourse:8080/
Unpause `ocw-themes-assets` pipeline and trigger a build for it. Wait for it to complete.
6. Copy the contents of ocw-www/ocw-studio.yaml from this branch into the `ocw-www` Website …
> Link and embed resources

- ocw-course-v2/ocw-studio.yaml
https://github.com/mitodl/hq/issues/3132
https://github.com/mitodl/ocw-hugo-themes/pull/1423
https://github.com/mitodl/ocw-studio/pull/2232
Removes `course_image_thumbnail` field from `ocw-studio` course config.
1. Checkout to this branch
2. Copy all the code from `ocw-course-v2/ocw-studio.yaml`
3. Start `ocw-studio` locally.
4. Paste the code into `WebsiteStarter` `ocw-course-v2` config from Django Admin.
5. Go to `localhost:8043/sites` and Create a new course site or open any existing one. Go to metadata from left navbar. You should no longer see Course Image Thumbnail field.
> Remove: course_image_thumbnail field

- ocw-course-v2/ocw-studio.yaml
Closes https://github.com/mitodl/hq/issues/4850
Removes `min: 1` value for department numbers from course metadata.
1. Copy code from `ocw-course-v2/ocw-studio.yaml` of this branch.
2. Spin up `ocw-studio`.
3. Go to `django-admin`, WebsiteStarters, and paste the code into config for `ocw-course-v2`.
4. Create a new course site locally or go to an existing one. Click on metadata from left menu. Have empty `Department Numbers` option and save it. It will work. (Otherwise it doesn't without this PR's changes - you can check locally or RC)
> Remove min: 1 value for department numbers

- ocw-course-v2/ocw-studio.yaml
Closes https://github.com/mitodl/hq/issues/4854
Remove RES from Available Departments in OCW course-v2 config for course metadata.
1. Copy code from `ocw-course-v2/ocw-studio.yaml` of this branch.
2. Spin up `ocw-studio`.
3. Go to `django-admin`, `WebsiteStarters`, and paste the code into config for `ocw-course-v2`.
4. Create a new course site locally. Click on metadata from left menu. You will no longer see an option for "RES" under "Department Numbers".
> Remove RES from Available Departments in OCW config

- ocw-course-v2/ocw-studio.yaml
Part of https://github.com/mitodl/hq/issues/5223
Add MIT Learn Topics Field to Course Metadata in OCW Studio. The topics are added from this spreadsheet: https://docs.google.com/spreadsheets/d/1Euu4ezPKeYkiTThvmxB5vFONFNG4fOULNW42F6qLuFI/edit?pli=1&gid=431773359#gid=431773359
(A) High Level Topics
1. Copy the code of `ocw-course-v2/ocw-studio.yaml` from this branch.
2. In your Studio's `.env`, set `OCW_HUGO_THEMES_BRANCH=ibrahim/5223/add-mit-learn-topics-in-coursedata`
3. Spin up OCW Studio locally.
4. Go to admin panel, website starters, `ocw-course-v2`, and paste the copied config to its config.
5. `docker-compose exec web ./manage.py upsert_theme_assets_pipeline` and unpause + start a build for the specific branch pipeline from `ocw-theme-assets` in `http://concourse:8080/`. Wait for …
> Add MIT Learn Topics Field to Course Metadata in OCW Studio

- ocw-www/ocw-studio.yaml
Part of https://github.com/mitodl/hq/issues/1384
Adds `Is Quote` Boolean Field for OCW Testimonial Quotes and relevant helping text.
We need the `is_quote` flag for new design of OCW Stories. If it's true, then the Quotes card is displayed with a clickable Modal instead of being redirected to the Story Single page.
Eg. The card in the middle:
Add the code from this branch to your local `ocw-www` website-starter from admin panel. Create a new story from your local `ocw-studio` and make sure the story created has a boolean `is_quote` field in the frontmatter of the markdown file.
Note: `is_quote` is used by this PR: https://github.com/mitodl/ocw-hugo-themes/pull/1460
> Add 'Is Quote' Boolean Field for OCW Testimonial Quotes

- ocw-course-v2/ocw-studio.yaml
- ocw-www/ocw-studio.yaml
Part of https://github.com/mitodl/hq/issues/5355
This pull request improves the management of external resources in OCW Studio:
* Adds `status` Field: Added the status field (`unchecked`, `valid`, `broken`, `check_failed`) to replace `is_broken`.
* Adds `wayback_url`,  to track Wayback Machine snapshots (and replace `backup_url`).
Test with steps given in https://github.com/mitodl/ocw-studio/pull/2308
> Add Status and Wayback Tracking Fields to External Resources

- ocw-course-v2/ocw-studio.yaml
- ocw-www/ocw-studio.yaml
Closes https://github.com/mitodl/hq/issues/6319
This PR sets default licensing pop-up warning for ERs to False.
Create a new ER in Studio locally with the updated config from this branch and make sure the `Include non-OCW licensing warning` is set to False by default.
> Set default licensing pop-up warning for ERs to False

- ocw-www/ocw-studio.yaml
Closes https://github.com/mitodl/hq/issues/6320
Removes name field in Studio for OCW Stories.
Create a new story with the updated config from this branch and make sure the `Name` field does not appear. Steps for this are:
1. Copy the `ocw-www` config code from this branch.
2. Spin up OCW-Studio locally.
3. Go to Django admin panel and `ocw-www` starter config.
4. Paste the copied config and save.
5. Go to `ocw-www` stories via Studio and click on Add Story.
6. Make sure Name isn't present in the fields.
> Remove Name field in Studio for OCW Stories

- ocw-www/ocw-studio.yaml
Part of https://github.com/mitodl/hq/issues/6895
For instructors, removed `headless: true` because it no longer creates `index.json` files during build.
For notifications,  replaced `headless: true` with:
```
_build:
list: always
render: never
```
so that they can be iterated over.
Checkout to this branch and copy the config to ocw-www starter locally in ocw-studio from django admin. Go to ocw-www site and create a notification and an instructor. Inspect the content markdown frontmatter from your GitHub ocw-www site repository.
Notification will have:
```
_build:
list: always
render: never
```
Instructor will not have `headless: true`.
> Remove headless: true

- .github/workflows/ci.yml
- Updated actions/checkout to v4
- Updated actions/setup-node to v4
- Updated Node.js version to 22 in CI workflow
- Updated actions/setup-python to v5
Just look at this PR's CI checks details
> Upgrade CI GitHub Actions and Node.js version
